/**
 * Security headers applied to every response. The CSP uses a nonce for inline
 * scripts generated by Next.js. Styles allow 'unsafe-inline' because Tailwind
 * and React inline style attributes require it.
 */
export function buildContentSecurityPolicy(nonce: string, options: { allowStripe: boolean; isDev: boolean }): string {
  const scriptSrc = ["'self'", `'nonce-${nonce}'`, "'strict-dynamic'"];
  if (options.isDev) scriptSrc.push("'unsafe-eval'");
  if (options.allowStripe) scriptSrc.push("https://js.stripe.com", "https://checkout.stripe.com");

  const connectSrc = ["'self'", "https://api.stripe.com", "https://checkout.stripe.com"];
  if (options.isDev) connectSrc.push("ws://localhost:*", "http://localhost:*");
  // Presigned uploads go straight to the storage bucket from the browser.
  connectSrc.push("https:");

  const frameSrc = options.allowStripe ? ["https://js.stripe.com", "https://checkout.stripe.com", "https://hooks.stripe.com"] : ["'none'"];

  const directives = [
    `default-src 'self'`,
    `script-src ${scriptSrc.join(" ")}`,
    `style-src 'self' 'unsafe-inline'`,
    `img-src 'self' blob: data: https:`,
    `media-src 'self' blob: data: https:`,
    `font-src 'self' data:`,
    `connect-src ${connectSrc.join(" ")}`,
    `frame-src ${frameSrc.join(" ")}`,
    `frame-ancestors 'none'`,
    `object-src 'none'`,
    `base-uri 'self'`,
    `form-action 'self'`,
    `worker-src 'self' blob:`,
    `manifest-src 'self'`,
  ];
  if (!options.isDev) directives.push("upgrade-insecure-requests");
  return directives.join("; ");
}

export const STATIC_SECURITY_HEADERS: Record<string, string> = {
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy": "camera=(self), microphone=(self), geolocation=(), payment=(self), usb=()",
  "X-DNS-Prefetch-Control": "off",
  "Cross-Origin-Opener-Policy": "same-origin",
};
